name: Auto Deploy on Retrain Trigger

on:
  push:
    branches: [ main ]
    paths:
      - app/model.pkl  # íº¨ Only run if model changes

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Stop Old Docker Container
      run: |
        docker stop ids-container || true
        docker rm ids-container || true

    - name: Build Docker Image
      run: docker build -t xai-ids .

    - name: Run Container
      run: docker run -d --name ids-container --env-file .env -p 8050:8050 xai-ids

