name: Build and Deploy Locally

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: self-hosted  # <--- This runs on your VM directly!

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Stop Old Docker Container (if any)
      run: |
        docker stop ids-container || true
        docker rm ids-container || true

    - name: Build Docker Image
      run: docker build -t xai-ids .

    - name: Run Container
      run: docker run -d --name ids-container --env-file .env -p 8050:8050 xai-ids

    - name: Run Inference Script
      run: docker exec ids-container python /app/model_runner.py

